package com.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.demo.model.User;
import com.demo.service.UserService;

/**
 * @author khoada
 *
 */
@Controller    // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UserController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserService userService;
	
	@PostMapping(path="") // Map ONLY GET Requests
	public @ResponseBody String create (@RequestParam String name, @RequestParam String email, @RequestParam(required=false) String about) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		userService.addNewUser(name, email, about);
		return "Saved";
	}
	
	@GetMapping(path="/index")
	public String index (Model model, @RequestParam(required=false) String email) {
		// This returns a JSON or XML with the users
		Iterable<User> users;
		if (email != null && !email.isEmpty())
			users = userService.findUserByEmail(email);
		else
			users = userService.findAllUser();
		model.addAttribute("users", users);
        return "user/index";
	}
}
